### ISSUE TITLE
Sentinel pattern for T5 causes build_and_test to fail

### ISSUE THREAD

**Issue by sejo95** [cpllab/lm-zoo#61]
I'm trying to include [T5 from Huggingface](https://huggingface.co/t5-base) in lm-zoo.

Its tokenizer uses "▁" as sentinel pattern at word beginnings. This causes build_and_test.sh to fail with "FAIL: test_surprisal_output_format (__main__.LMProcessingTest)" because SURPRISAL_RE does not include that character.

https://github.com/cpllab/lm-zoo/blob/8530bb403b83d33b138680054afb5170ffc3f324/test.py#L28-L30

A possible solution for this would be to simply add the character to SURPRISAL_RE:
`SURPRISAL_RE = re.compile(r"sentence_id\ttoken_id\ttoken\tsurprisal\n"
                           "(\d+\s+\d+\s+[\w.<>▁]+\s+[-\d.]+\n)+(\d+\s+\d+\s+[\w.<>▁]+\s+[-\d.]+)",
                          flags=re.MULTILINE)`

**Comment by hans** [comment]
Hi @sejo95 , thanks for the note. This fix has been included in a new release 1.2.3, now available on PyPI.
