### ISSUE TITLE
Add bos_token to lm-zoo for gpt2 (and any other models that need it)

### ISSUE THREAD

**Issue by rlevy** [cpllab/lm-zoo#67]
We determined that `lm-zoo`'s `gpt2` implementation matches HuggingFace's implementation to a good number of significant digits, but only when the beginning-of-sequence token `bos_token` is *omitted* from the sequence passed to HuggingFace. We need to confirm whether including or omitting `bos_token` is the best practice (most likely, including it is the best practice); if including it is the best practice, we should modify our invocation of `gpt2` in `lm-zoo` to match this.

**Comment by hans** [comment]
there's really no ground truth about the BOS token. In fact .. the original OpenAI implementation is even internally inconsistent, using BOS in its [unconditional sampling code](https://github.com/openai/gpt-2/blob/master/src/generate_unconditional_samples.py#L60) but not in its [conditional sampling code](https://github.com/openai/gpt-2/blob/master/src/interactive_conditional_samples.py#L61). We don't have access to the original training code/dataset, but the model seems to do just fine anyway in both regimes.

But I think matching with Huggingface is a good rule of thumb, since that implementation is far more popular than the original.
I'll switch over lm-zoo / document / release accordingly today.

**Comment by hans** [comment]
Just to complicate this -- I played with the vanilla Huggingface GPT2 and it actually doesn't add BOS, even with `add_special_tokens=True`. Plenty of confusion about this in the community e.g. [here](https://github.com/huggingface/transformers/issues/3311).
I'd still say incorporating BOS is better for our purposes / the purposes of lm-zoo. I'll just document this clearly on the site.

**Comment by hans** [comment]
Not totally fixed yet -- looks like deps are breaking upon rebuilding transformers-base. Will look into this tomorrow.
There is also something breaking in `unkify`. Both show up in integration test failures below.

```
INFO:__main__:Loading tokenizer
INFO:__main__:Reading sentences from <_io.TextIOWrapper name='/tmp/tmpxpk_v855' mode='r' encoding='utf-8'>
INFO:__main__:Loading tokenizer
INFO:__main__:Reading sentences from <_io.TextIOWrapper name='/tmp/tmpxpk_v855' mode='r' encoding='utf-8'>
Traceback (most recent call last):
  File "/opt/transformers/get_surprisals.py", line 19, in <module>
    from transformers import AutoModelForCausalLM, AutoTokenizer
ImportError: cannot import name 'AutoModelForCausalLM' from 'transformers' (/opt/conda/lib/python3.7/site-packages/transformers/__init__.py)
E.
======================================================================
ERROR: test suite for <class '__main__.LMProcessingTest'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/opt/conda/lib/python3.7/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/opt/conda/lib/python3.7/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/opt/conda/lib/python3.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/test.py", line 88, in setUpClass
    cls.surprisals_output = subprocess.check_output(["get_surprisals", text_f.name]).decode("utf-8")
  File "/opt/conda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/opt/conda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['get_surprisals', '/tmp/tmpxpk_v855']' returned non-zero exit status 1.
-------------------- >> begin captured stdout << ---------------------
== tokenize /tmp/tmpxpk_v855
<|endoftext|> This Ġis Ġa Ġtest Ġsentence . <|endoftext|>
<|endoftext|> This Ġis Ġanother Ġtest Ġsentence . <|endoftext|>
<|endoftext|> This Ġis Ġa Ġthird Ġsentence Ġwith Ġan Ġa ors nar nt Ġtoken . <|endoftext|>
<|endoftext|> This Ġis Ġa Ġsentence Ġwith Ġa Ġspecial ĠâĢ ľ Ġtoken . <|endoftext|>



== unkify /tmp/tmpxpk_v855
1 0 0 0 0 0 0 1
1 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 0 0 0 1



== get_surprisals /tmp/tmpxpk_v855

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 1 test in 5.270s

FAILED (errors=1)
```
